server:
   servlet:
      context-path: /workshop
   port: 9090
   error:
      include-message: always
spring:
   flyway:
      locations: classpath:db/migrations
      defaultSchema: play_schema   
   datasource:
      url: jdbc:postgresql://localhost:5432/workshop
      username: ${DATABASE_USER:postgres}
      password: ${DATABASE_PASSWORD:postgres}
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            default_schema: play_schema
services:
   bet:
      url: http://localhost:8080/workshop/bets
