server:
   servlet:
      context-path: /workshop
   port: 9090
spring:
   sql:
      init:
         mode: always
         schema-locations: classpath:schema.sql
         continue-on-error: true
   datasource:
      url: jdbc:postgresql://custompostgresql:5432/workshop
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            default_schema: play_schema
services:
   bet:
      url: http://customservicebet:8080/workshop/bets