server:
   servlet:
      context-path: /workshop
   port: 9090
   error:
      include-message: always
spring:
   flyway:
      locations: classpath:db/migrations
      defaultSchema: play_schema  
   datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            '[format_sql]': true
            '[default_schema]': play_schema
services:
   bet:
      url: http://${SERVICE_BET_HOSTNAME}/workshop/bets
