name: Java CI
run-name: ${{ github.actor }} is starting the execution of backend pipeline "Java CI" with GitHub Actions
on:
  push:
    branches: [ "develop", "feature/**" ]
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  build:
    name: 'Backend CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify sonar:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Get AWS Secrets by Name
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            pro/workshop1/secrets
          parse-json-secrets: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Maven project version
        run: |
          echo "MAVEN_PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> "$GITHUB_ENV"
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          target: production
          build-args: |
            "env_database_url=jdbc:postgresql://${{ env.PRO_WORKSHOP1_SECRETS_DATABASE_HOSTNAME }}:5432/workshop"
            "env_database_user=dbadmin"
            "env_database_password=${{ env.PRO_WORKSHOP1_SECRETS_DATABASE_PASSWORD }}"
            "env_service_bet_hostname=workshop1-service-msbet.default.svc.cluster.local"
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}/workshop1:ms-play_v${{ env.MAVEN_PROJECT_VERSION }}
